# Generated by Django 4.2.3 on 2023-07-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_created_at_blogpost_story_blogpost_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
