# Generated by Django 4.2.3 on 2023-07-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blogpost_is_trending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['created_at']},
        ),
    ]
